name: tests

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - setup.py
      - pyproject.toml
      - MANIFEST.in
      - tests/**
      - safety_gymnasium/**
      - .github/workflows/tests.yml
  # Allow to trigger the workflow manually
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  test-ubuntu:
    name: Test for Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        # TODO: add Python 3.11 to test matrix
        python-version: ["3.8", "3.9", "3.10"]
      fail-fast: false
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          update-environment: true

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Install rendering dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libosmesa6-dev
          sudo apt-get install python3-opengl

      - name: Set MUJOCO_GL
        run: |
          echo "MUJOCO_GL=osmesa" >> "${GITHUB_ENV}"
          echo "PYOPENGL_PLATFORM=osmesa" >> "${GITHUB_ENV}"

      - name: Install Safety-Gymnasium
        run: |
          python -m pip install -vvv --editable '.[test]'

      - name: Test with pytest
        run: |
          make pytest
